#!/ffp/bin/sh
# ----------------------------------------------
# Retrieve dns-323 temperature sensor values
# for internal, disk1 and disk2
#
# Used by http://bernaerts.dyndns.org/nas/...
#
# Depends on packages : 
#   * smartmontools
#
# Parameters :
#   $1 - sensor type (internal, disk1 or disk2)
#
# 24/07/2014, V1.0 - Creation by N. Bernaerts
# ----------------------------------------------

# read temperature for $1
case $1 in
  # read case internal temperature
  internal)
    # read temperature in Farenheit and convert it to celcius
    RESULT=`temperature g 0 | tail -n 1 | sed 's/^.* = \([0-9]*\).*$/\1/g'`
    RESULT=`expr $RESULT - 32`
    RESULT=`expr $RESULT \* 5 / 9`
    echo $RESULT
    ;;

  # read disk1 (/dev/sda) temperature
  disk1)
    RESULT=`smartctl -A --device=marvell /dev/sda | grep "^194.*" | sed 's/^.*- *\([0-9]*\).*$/\1/g'`
    [ "$RESULT" = "" ] && echo "U" || echo $RESULT
    ;;

  # read disk2 (/dev/sdb) temperature
  disk2)
    RESULT=`smartctl -A --device=marvell /dev/sdb | grep "^194.*" | sed 's/^.*- *\([0-9]*\).*$/\1/g'`
    [ "$RESULT" = "" ] && echo "U" || echo $RESULT
    ;;

  # default : nothing to do
  *)
esac

# end
exit 0
